[package]
name = "mesh-testing"

version = { workspace = true }
edition = { workspace = true }

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
#
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test    = { workspace = true }
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
cosmwasm-storage = { workspace = true }
schemars         = { workspace = true }
serde            = { workspace = true }
thiserror        = { workspace = true }
meta-staking     = { workspace = true }
mesh-consumer    = { workspace = true }
mesh-provider    = { workspace = true }
mesh-slasher     = { workspace = true }
