[package]
name = "mesh-ibc"

version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["ibc3"] }
schemars        = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }
